### PR TITLE
save missing starters to file after request

### PR DESCRIPTION
**Pull request by bahalbach**
I often encounter missing starter errors when loading the pbp data from disk that aren't covered by overrides. So I put in code to update missing_period_starters.json after the request is made. 

I've been using the stats.nba.com endpoint, but I think this would be a good idea for the other endpoints as well.

Usually one team is covered in the override file, but the other team is causing errors.

### CODE REVIEW

**Comment by bahalbach** [comment]
I also added print statements to see when periods were missing starters. You probably won't want to commit those changes.

**Comment by dblackrun** [comment]
Where are you seeing this happen? It's not something I have seen before.

**Comment by bahalbach** [comment]
I was seeing this in games where one team was missing players for a period (like 0020100916, 0020200992, or 0040200233). The team that was not missing players in the pbp data would be the team that caused the error. 

I think what might be causing the issue is those players not appearing as player1, so they don't have a team id, and _split_up_starters_by_team() is done before the other teams players are loaded from the overrides file.

**Comment by dblackrun** [comment]
What version are you using? I had no issues any of those games both using overrides and without any overrides. The missing period starters override is more of a legacy thing from before I added in making the request by boxscore range. I'm not sure if it is even necessary for any games anymore.

**Comment by bahalbach** [comment]
I'm using version 1.3.3. The missing period starters are resolved by making a boxscore request, but that request would sometimes timeout for me, so I figured it would be better to save the data.

**Comment by dblackrun** [comment]
What happens if you increase the timeout or add a delay before making the request?

**Comment by bahalbach** [comment]
A delay would also resolve the timeout. I was just thinking it would be better to be able to cache the starters once you got them from the request once so you wouldn't need to keep making it.

**Comment by dblackrun** [comment]
From my experience timeouts tend happen with if you are making too many requests within a short period of time.

I would rather avoid having to use the overrides file since I would like to see if that can be completely deprecated at some point.

I think increasing the timeout is a good idea.

**Pull request closed without merging**
